name: unittest

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Test Blockizer
        run: |
          python -m unittest tests/test_blockizer.py
      - name: Test Complex Case
        run: |
          python -m unittest tests/test_complex_case.py
      